FROM ubuntu:18.04

LABEL org.opencontainers.image.authors="juraj.vijtiuk@sartura.hr,andrej.gardijan@sartura.hr"

RUN \
      apt-get update && apt-get install -y \
      git \
      cmake \
      build-essential \
      vim \
      supervisor \
      zlib1g-dev \
      libpcre3-dev \
      libpcre2-dev \
      pkg-config \
      libavl-dev \
      libev-dev \
      libprotobuf-c-dev \
      protobuf-c-compiler \
      libssl-dev \
      swig \
      python-dev

# add netconf user
RUN \
      adduser --system netconf && \
      echo "netconf:netconf" | chpasswd

# set root password
# ensure that an unexpected error prevents the build from succeeding
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN \
      echo "root:root" | chpasswd

# generate ssh keys for netconf user
RUN \
      mkdir -p /home/netconf/.ssh && \
      ssh-keygen -A && \
      ssh-keygen -t dsa -P '' -f /home/netconf/.ssh/id_dsa && \
      cat /home/netconf/.ssh/id_dsa.pub > /home/netconf/.ssh/authorized_keys

# use /opt/dev as working directory
RUN mkdir /opt/dev
WORKDIR /opt/dev

# libyang
RUN \
      git clone https://github.com/CESNET/libyang.git && \
      cd libyang && mkdir build && cd build && \
      git checkout master && \
      cmake -DCMAKE_BUILD_TYPE:String="Release" -DENABLE_BUILD_TESTS=OFF .. && \
      make -j$(nproc) && \
      make install && \
      ldconfig

#libssh
RUN \
      cd /opt/dev && \
      git clone https://git.libssh.org/projects/libssh.git && cd libssh && \
      mkdir build && cd build && \
      cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE="Debug" -DWITH_ZLIB=ON -DWITH_NACL=OFF -DWITH_PCAP=OFF .. && \
      make -j$(nproc) && \
      make install && \
      ldconfig

# sysrepo
RUN \
      git clone https://github.com/sysrepo/sysrepo.git && \
      cd sysrepo && mkdir build && cd build && \
      git checkout master && \
      cmake -DCMAKE_BUILD_TYPE:String="Release" -DENABLE_TESTS=OFF -DREPOSITORY_LOC:PATH=/etc/sysrepo \
      -DGEN_LANGUAGE_BINDINGS=OFF -DENABLE_NACM=OFF -DBUILD_EXAMPLES=OFF \
      -DREQUEST_TIMEOUT=300 -DCOMMIT_VERIFY_TIMEOUT=300 \
      -DGET_SUBTREE_CHUNK_CHILD_LIMIT=200000 \
      .. && \
      make -j$(nproc) && \
      make install && \
      ldconfig

# libnetconf2
RUN \
      git clone https://github.com/CESNET/libnetconf2.git && \
      cd libnetconf2 && mkdir build && cd build && \
      git checkout master && \
      cmake -DCMAKE_BUILD_TYPE:String="Release" -DENABLE_BUILD_TESTS=OFF \
      -DREAD_INACTIVE_TIMEOUT=300 -DREAD_ACTIVE_TIMEOUT=300 \
      .. && \
      make -j$(nproc) && \
      make install && \
      ldconfig

# netopeer2
RUN \
      cd /opt/dev && \
      git clone https://github.com/CESNET/Netopeer2.git && \
      cd Netopeer2 && \
      mkdir build && cd build && \
      git checkout master && \
      cmake -DCMAKE_BUILD_TYPE:String="Release" .. && \
      make -j$(nproc) && \
      make install && \
      ldconfig

# sysrepo-snabb-plugin
RUN \
      git clone https://github.com/sysrepo/sysrepo-snabb-plugin.git && \
      cd sysrepo-snabb-plugin && mkdir build && cd build && \
      git checkout master && \
      cmake -DCMAKE_BUILD_TYPE:String="Release" -DPLUGIN:BOOL=ON -DSR_PLUGINS_DIR:PATH=/usr/local/bin/ -DYANG_MODEL:String="snabb-softwire-v2" .. && \
      make -j$(nproc) && \
      make install && \
      ldconfig

# snabb
RUN \
      git clone https://github.com/Igalia/snabb.git && \
      cd snabb && \
      git checkout lwaftr && \
      make -j$(nproc) && \
      make install && \
      ldconfig

RUN \
      apt-get update && apt-get install -y \
      # general tools
      systemd \
      valgrind \
      gdb

# install snabb YANG models
RUN \
      sysrepoctl --install /opt/dev/snabb/src/lib/yang/snabb-softwire-v2.yang

# setup systemd
ENV \
      container docker
RUN \
      apt-get update && apt-get install -y systemd apt-utils && \
      (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done) && \
      rm -f /lib/systemd/system/multi-user.target.wants/* && \
      rm -f /etc/systemd/system/*.wants/* && \
      rm -f /lib/systemd/system/local-fs.target.wants/* && \
      rm -f /lib/systemd/system/sockets.target.wants/*udev* && \
      rm -f /lib/systemd/system/sockets.target.wants/*initctl* && \
      rm -f /lib/systemd/system/basic.target.wants/* && \
      rm -f /lib/systemd/system/anaconda.target.wants/*

VOLUME [ “/sys/fs/cgroup” ]
CMD [“/sbin/init”]

# setup systemd
RUN \
      echo "export PATH=\$PATH:/opt/scripts" >> /root/.bashrc

RUN \
      mkdir -p /opt/snabb/conf

COPY \
      ./scripts/lwaftr.sh /opt/snabb/conf

COPY \
      ./systemd/* /lib/systemd/system/

RUN \
      systemctl enable sysrepod.service && \
      systemctl enable sysrepo-plugind.service && \
      systemctl enable netopeer2-server.service && \
      systemctl enable lwaftr.service

ENV EDITOR vim
EXPOSE 830
